name: 'Check for newly added scripts'

on:
  push:
    branches:
      - master
    paths:
      - scripts/**
      
jobs:
  check-for-new-scripts:
    runs-on: ubuntu-latest
    permissions:
        issues: write
    env:
      folders: ""
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1
        
      - name: List Folders
        run: |
        
          folders=""
          
          for path in ${{ steps.changed-files.outputs.all_changed_files }}; do
                  if echo $path | grep "scripts/.*" >/dev/null; then
                          folder=`echo $path | awk -F"/" '{print $2}'`
                          if [ `echo $folders | grep -c $folder` -eq 0 ]; then
                                  folders+="$folder "
                          fi
                  fi
          done
          
          ${{ env.folders=$folders }}
          
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "prashanth4"
          labels: "bug"
          title: "Team sync"
          body: |
            ### Agenda
            {{$env.folders}}
            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording

            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
          pinned: false
          close-previous: false
          
#          curl -A 'Mandrill-Curl/1.0' -d '{"key":"FRFOkai6JHMaPKDeY57feg","message":{"html":"<p> Upgrade scripts were added/modified at this location https://github.com/Openprise/openprise/tree/master/daass/server/scripts/</p>","subject":"New DB Scripts Added to $folders","from_email":"no-reply@openprisetech.com","from_name":"Github Actions","to":[{"email":"prashanth.bodduna@openprisetech.com"}]}}' 'https://mandrillapp.com/api/1.0/messages/send.json'
          
          
