name: 'Check for new added scripts'

on:
  push:
    branches:
      - master
    paths:
      - scripts/*
      
jobs:
  check-for-new-scripts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: curl -A 'Mandrill-Curl/1.0' \
                  -d '{
                        "key":"FRFOkai6JHMaPKDeY57feg",
                        "message":{
                          "html":"<p> Upgrade scripts were added/modified at this location https://github.com/Openprise/openprise/tree/master/daass/server/scripts/</p>",
                          "subject":"New DB Scripts Added<EOM>",
                          "from_email":"no-reply@openprisetech.com",
                          "from_name":"Github Actions",
                          "to":[{"email":"prashanth.bodduna@openprisetech.com"}]}
                       }' 'https://mandrillapp.com/api/1.0/messages/send.json'
      - run: echo "This job's status is ${{ job.status }}."
