name: 'Check for newly added scripts'

on:
  push:
    branches:
      - master
    paths:
      - scripts/**
      
jobs:
  check-for-new-scripts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      
      - uses: actions/checkout@v3
      
      - name: Get files changed
        id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        
      - name: list files
        run: |
          folders=""
          
          for path in $paths; do
                  if echo $path | grep "scripts/.*" >/dev/null; then
                          folder=`echo $path | awk -F"/" '{print $2}'`
                          if [ `echo $folders | grep -c $folder` -eq 0 ]; then
                                  folders+="$folder "
                          fi
                  fi
          done
          
          echo $folders
          
#          curl -A 'Mandrill-Curl/1.0' -d '{"key":"FRFOkai6JHMaPKDeY57feg","message":{"html":"<p> Upgrade scripts were added/modified at this location https://github.com/Openprise/openprise/tree/master/daass/server/scripts/</p>","subject":"New DB Scripts Added to ${folders}","from_email":"no-reply@openprisetech.com","from_name":"Github Actions","to":[{"email":"prashanth.bodduna@openprisetech.com"}]}}' 'https://mandrillapp.com/api/1.0/messages/send.json'
          
          
