name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1

      - name: List all changed files
        run: |
          folders=""
          
          for path in ${{ steps.changed-files.outputs.all_changed_files }}; do
                  if echo $path | grep "scripts/.*" >/dev/null; then
                          folder=`echo $path | awk -F"/" '{print $2}'`
                          if [ `echo $folders | grep -c $folder` -eq 0 ]; then
                                  folders+="$folder "
                          fi
                  fi
          done
          
          echo $folders
